import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/header/header";
import LayoutBox from "@/components/common/layout";
import Footer from "@/components/footer/footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "100xDevs",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={ inter.className }>
        <Header />
        <div className="flex">
          <LayoutBox />
          { children }
        </div>
      </body>
    </html>
  );
}
